2024-06-18 11:55:16,892 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Current SDK version is 0.17.2
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Configure stats pid to 22467
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Loading settings from /home/harsh/.config/wandb/settings
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Loading settings from /home/harsh/Downloads/PROJECTS/road_detection_unet/wandb/settings
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_init.py:_log_setup():520] Logging user logs to /home/harsh/Downloads/PROJECTS/road_detection_unet/wandb/run-20240618_115516-3nfitrn2/logs/debug.log
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_init.py:_log_setup():521] Logging internal logs to /home/harsh/Downloads/PROJECTS/road_detection_unet/wandb/run-20240618_115516-3nfitrn2/logs/debug-internal.log
2024-06-18 11:55:16,893 INFO    MainThread:22467 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fac736c0ee0>
2024-06-18 11:55:16,894 INFO    MainThread:22467 [wandb_init.py:init():560] calling init triggers
2024-06-18 11:55:16,894 INFO    MainThread:22467 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-18 11:55:16,894 INFO    MainThread:22467 [wandb_init.py:init():610] starting backend
2024-06-18 11:55:16,894 INFO    MainThread:22467 [wandb_init.py:init():614] setting up manager
2024-06-18 11:55:16,898 INFO    MainThread:22467 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-18 11:55:16,899 INFO    MainThread:22467 [wandb_init.py:init():622] backend started and connected
2024-06-18 11:55:16,903 INFO    MainThread:22467 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-18 11:55:16,908 INFO    MainThread:22467 [wandb_init.py:init():711] updated telemetry
2024-06-18 11:55:16,938 INFO    MainThread:22467 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-18 11:55:17,501 ERROR   MainThread:22467 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-18 11:55:17,501 ERROR   MainThread:22467 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-18 11:56:18,741 WARNING MsgRouterThr:22467 [router.py:message_loop():77] message_loop has been closed
