2024-06-18 12:11:58,625 INFO    StreamThr :22588 [internal.py:wandb_internal():85] W&B internal server running at pid: 22588, started at: 2024-06-18 12:11:58.624810
2024-06-18 12:11:58,626 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status
2024-06-18 12:11:58,629 INFO    WriterThread:22588 [datastore.py:open_for_write():87] open: /home/harsh/Downloads/PROJECTS/road_detection_unet/wandb/run-20240618_121158-x3cfap06/run-x3cfap06.wandb
2024-06-18 12:11:58,630 DEBUG   SenderThread:22588 [sender.py:send():379] send: header
2024-06-18 12:11:58,649 DEBUG   SenderThread:22588 [sender.py:send():379] send: run
2024-06-18 12:11:59,208 ERROR   SenderThread:22588 [internal_api.py:execute():344] 403 response executing GraphQL.
2024-06-18 12:11:59,208 ERROR   SenderThread:22588 [internal_api.py:execute():345] {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-06-18 12:11:59,209 ERROR   SenderThread:22588 [sender.py:send_run():1009] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 1007, in send_run
    server_run = self._init_run(run, config_value_dict)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 1079, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upsert_run
    response = self.gql(
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/util.py", line 968, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/harsh/anaconda3/envs/unet_env/lib/python3.8/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-06-18 12:11:59,567 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:03,649 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:04,210 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:04,568 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:08,650 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:09,211 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:09,569 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:13,651 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:14,212 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:14,570 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:18,652 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:19,212 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:19,570 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:23,652 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:24,213 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:24,571 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:28,653 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:29,213 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:29,572 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:33,654 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:34,214 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:34,572 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:38,655 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:39,215 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:39,573 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:43,656 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:44,217 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:44,575 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:48,657 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:49,218 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:49,576 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:53,658 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:54,218 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:54,577 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:58,659 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:12:59,219 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:12:59,577 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:03,660 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:13:04,219 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:04,578 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:08,661 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:13:09,220 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:09,579 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:13,662 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:13:14,222 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:14,580 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:18,663 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:13:19,222 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:19,581 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:23,664 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: keepalive
2024-06-18 12:13:24,223 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:24,582 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:28,665 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: cancel
2024-06-18 12:13:28,665 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: cancel
2024-06-18 12:13:29,223 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:29,582 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:34,224 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:34,583 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:39,196 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: shutdown
2024-06-18 12:13:39,196 INFO    HandlerThread:22588 [handler.py:finish():882] shutting down handler
2024-06-18 12:13:39,225 DEBUG   HandlerThread:22588 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 12:13:39,584 INFO    SenderThread:22588 [sender.py:finish():1608] shutting down sender
2024-06-18 12:13:39,584 INFO    WriterThread:22588 [datastore.py:close():296] close: /home/harsh/Downloads/PROJECTS/road_detection_unet/wandb/run-20240618_115623-0336bqgf/run-0336bqgf.wandb
